### ISSUE TITLE
Support more than just the standard integer types in is_supported_type, is_signed, and make_unsigned

### ISSUE THREAD

**Issue by gustedt** [rcseacord/cmp_int#3] opened 2021-11-09 14:12 UTC
besides the naming convention issue, this macro is superfluous and restricts the usage of your macros to the 6 standard integer types

**Comment by AaronBallman** [comment] 2021-11-10 19:53
I don't think this is actually superfluous, but the point you raise about restricting to specific integer types is valid. `make_unsigned` exists to compile cleanly at high warning levels (like `-Wall -Wextra -pedantic`). Without it, we'll get sign/unsigned comparison warnings.

However, there may be tricks we can apply to get the unsigned type through implicit conversions without triggering compiler warnings. But given that we constrain the interface to only accept those standard integer types already, we should fix both `make_unsigned` and `is_supported_type` at the same time.

I'm going to edit the title of the bug based on this.

**Comment by AaronBallman** [comment] 2021-11-10 19:56
Oh, hey, that's exactly what #4 is about... so I'm going to close this one as a dupe of the other request.

**Closed as completed by AaronBallman** 2021-11-10 19:56 UTC
Labels: enhancement
